### ISSUE TITLE
[FE] AllClothes.vue 테스트 과정에서 오류 해결

### ISSUE THREAD

**Issue by kjthegarden** [WoodNeck/mxm#17]
(다른 문제로 수정했습니다.)
![2018-05-11 11-18-32](https://user-images.githubusercontent.com/22138081/39903225-1f0682ca-550d-11e8-8881-8d97134298c6.png)

- png로 끝나는 것에 뭐가 문제가 있는 것 같은데 어떤 문제인지 확인을 못하겠네요. 
- 테스트코드까지는 푸시했습니다. 계속 수정해볼 예정이에요.

**Comment by WoodNeck** [comment]
require구문이 jest test 파일에서 원활하게 동작하지 않는 것으로 보이는데
해결방법은
1) require에 jest의 [mocking](https://facebook.github.io/jest/docs/en/jest-object.html#jestdomockmodulename-factory-options)을 사용하거나
2) [이곳](https://github.com/facebook/jest/issues/2663#issuecomment-317109798)에 나와있는 방법으로 해결 가능합니다.

하지만 저희 경우에는 현재 만드신 AllClothes.vue파일에서처럼 static asset을 불러오는 형태가 아니라,
Backend로부터 이미지의 url을 받아오는 형태로 저장된 이미지를 받아올거에요
이 경우 `<img>`태그에 `src="url"`의 prop을 붙이는 형태로  구현되기 때문에, 현재 발생한 오류는 발생하지 않을겁니다

그래서, 현재 만드신 AllClothes 테스팅은 당장은 큰 의미가 없을 것 같습니다. 핵심적인 기능이 아직 구현되지 않았으니까요.
제 생각엔 저 부분의 오류는 무시하시고, Backend랑 통신하여 이미지를 받아오는것까지 먼저 구현하신 다음에 테스트를 진행하는게 더 나아보이네요

**Comment by WoodNeck** [comment]
Backend와의 통신을 위한 Asynchronous api 작성을 먼저 하실 생각이시라면, 확인하시고 issue close부탁드립니다.

제가 미리 찾아둔 api 작성용 라이브러리를 몇개 같이 남깁니다.
1. [https://github.com/axios/axios](https://github.com/axios/axios)
2. [https://github.com/mikeal/r2](https://github.com/mikeal/r2)
3. [https://github.com/rapidjs/rapid.js](https://github.com/rapidjs/rapid.js)

**Comment by kjthegarden** [comment]
@WoodNeck 
넵 확인했습니다~
