### ISSUE TITLE
[BE] google login 관련 문제 해결

### ISSUE THREAD

**Issue by yskim5892** [WoodNeck/mxm#9]
* login된 상태에서 logout한 후 다른 google 계정으로 login하더라도 기존의 계정으로 login됨
* google 계정으로 login한 상태에서 django 페이지에 HTML format으로 POST할 시 모든 attribute가 default 값으로 POST됨

**Comment by YunSunLee** [comment]
- login된 상태에서 logout한 후 다른 google 계정으로 login하더라도 기존의 계정으로 login됨
=> 원래 google login의 동작이 그러함
- google 계정으로 login한 상태에서 django 페이지에 HTML format으로 POST할 시 모든 attribute가 default 값으로 POST됨
=> 프론트엔드에서 POST시 문제 없음.
